name: dropandgouser
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  cloud_firestore: ^4.4.3
  connectivity_plus: ^3.0.2
  country: ^2.0.7
  cron: ^0.5.1
  cupertino_icons: ^1.0.5
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage:
  permission_handler: ^10.2.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^9.0.0
  flutter_gen: ^5.1.0+1
  flutter_local_notifications: ^14.0.0+2
  flutter_screenutil: ^5.4.0+1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  form_builder_validators: ^9.0.0
  formz: ^0.4.1
  fpdart: ^0.3.0
  get_it: ^7.2.0
  geolocator: ^9.0.2
  go_router: ^6.0.6
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  local_auth: ^2.1.6
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.6
  intl: ^0.18.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  just_audio: ^0.9.32
  just_audio_background: ^0.0.1-beta.9
  path_provider: ^2.0.13
  path: ^1.8.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  sqflite: ^2.2.8+4
  shimmer: ^2.0.0
  url_launcher: ^6.1.9

#dependency_overrides:
#  match: ^0.4.1
#  test_api: 0.4.16

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^5.0.0
  rename: ^2.1.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/audio/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/PoppinsMedium500.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold600.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700